apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lemonade-demo-admin-rb
  namespace: lemonade-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: lemonade-demo-admin
  namespace: lemonade-demo